export const skills = [
  "Html",
  "Css",
  "Js",
  "React",
  "Sass",
  "Bootstrap",
  "Tailwindcss",
  "Typescript ",
  "Scrum",
  "Git Flow",
];

export const projects = [
  {
    title: "Devsafio",
    subtitle: "MERN stack",
    description: "Devsafio SPA",
    image: "./project-1.gif",
    link: "https://devsafio.com/",
  },
  {
    title: "My pizza",
    subtitle: "React + vite",
    description: "Tienda de pizza",
    image: "./project-1.gif",
    link: "https://mypizza-c88f.vercel.app/",
  },
  {
    title: "Calculadora App",
    subtitle: "React + Vite",
    description: "Calculadora convencional",
    image: "./project-1.gif",
    link: "https://calculadorapp.vercel.app/",
  },
  {
    title: "WoW Music Player",
    subtitle: "Vue + Bulma",
    description: "Reproductor de Musica",
    image: "./project-1.gif",
    link: "https://splendorous-croissant-f4a2fe.netlify.app/",
  },
  {
    title: "Movie Center",
    subtitle: "TMDB API + REACT",
    description: "Probando hooks de React",
    image: "./project-5.gif",
    link: "https://movies-api-tox3.vercel.app/",
  },
  {
    title: "Tic-Tac-Toe",
    subtitle: "REACT + Tailwind CSS",
    description: "Simple",
    image: "./project-5.gif",
    link: "https://tic-tac-toe-pi-lyart.vercel.app/",
  },
  {
    title: "Rick & Morty Api",
    subtitle: "React + vite",
    description: "Consumiendo api de rick & Morty",
    image: "./project-2.gif",
    link: "https://rickandmorty-bice.vercel.app/",
  },
  {
    title: "Clima App",
    subtitle: "React + Vite + Weather API",
    description: "Consumiendo api del clima",
    image: "./project-3.gif",
    link: "https://climapp-phi.vercel.app/",
  },
  {
    title: "Natural-Pic",
    subtitle: "React Hooks",
    description: "Probando hook de React",
    image: "./project-5.gif",
    link: "https://natural-pic.vercel.app/",
  },
];
